name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🎁 새로운 기능이 추가되었어요'
    label: '🎁 feature'
  - title: '🐞 자잘한 버그를 수정했어요'
    label: '🐞 hotifx'
  - title: '🐬 코드를 개선했어요'
    label:
      - '📋 docs'
      - '🧼 refactor'
      - '🪄 setting'
      - '🎫 test'
      - '🚀 deploy'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## 이번 버전의 변경사항은 아래와 같아요
  ---
  $CHANGES
no-changes-template: '변경사항이 없어요'
