services:
  mysql-docker:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'packy'
      MYSQL_ROOT_PASSWORD: '1234'
      TZ: Asia/Seoul
    container_name: 'packy-mysql'
    ports:
      - '3306:3306'
    volumes:
      - /Users/leeeeeyeon/data/db-docker/data/mysql:/var/lib/mysql

  redis-docker:
    image: redis:latest
    container_name: 'packy-redis'
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    volumes:
      - /Users/leeeeeyeon/data/db-docker/data/redis:/data
